replaces ajax `success` function with `done`
* `success` appears to be deprecated in favor of `done`
* leaving in `success` caused `Uncaught TypeError: $.ajax(...).success
is not a function`